apiVersion: v1
kind: Service
metadata:
  name: webmcp
  namespace: lulu
  annotations:
    cloud.google.com/backend-config: '{"default": "webmcp-backend-config"}'
spec:
  type: NodePort
  selector:
    app: webmcp
  ports:
    - port: 80
      targetPort: 8080
